var exercitia = {}
exercitia.data = {
    '1': [
        'ūnus',
        'duo',
        'trēs',
        'quattuor',
        'quīnque',
        'sex',
        'septem',
        'octō',
        'novem',
        'decem',
    ],
    '10+': [
        'ūndecim',
        'duodecim',
        'tredecim',
        'quattuordecim',
        'quīndecim',
        'sēdecim',
        'septendecim',
        'duodēvīgintī',
        'ūndēvīgintī',
        'vīgintī',
    ],
    '*10': [
        'decem',
        'vīgintī',
        'trīgintā',
        'quadrāgintā',
        'quīnquāgintā',
        'sexāgintā',
        'septuāgintā',
        'octōgintā',
        'nōnāgintā',
        'centum',
    ],
    '*100': [
        'centum',
        'ducentī',
        'trecentī',
        'quadringentī',
        'quīngentī',
        'sescentī',
        'septingentī',
        'octingentī',
        'nōngentī',
        'mīlle'
    ]
}